apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: flux2
  secretRef:
    name: flux-system
  url: https://github.com/iceowlbeer/cl2023-flux