apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: loki
  namespace: flux-system
spec:
  dependsOn:
    - name: agent
      namespace: flux-system
    - name: monitoring-stack
      namespace: flux-system
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: "./infrastructure/monitoring/loki"
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-config
  prune: true