apiVersion: v1
kind: Service
metadata:
  name: loki-gossip-ring
  namespace: monitoring
  labels:
    app: loki
    release: loki
spec:
  clusterIP: None
  ports:
    - port: 7946
      protocol: TCP
      name: gossip
      targetPort: http-metrics
      appProtocol: http
    - name: grpc-submit
      port: 9095
      targetPort: grpc-submit
      protocol: TCP
      appProtocol: TCP
  selector:
    app: loki
    release: loki